create table
  public.cart_items (
    id bigint generated by default as identity,
    quantity integer null default 0,
    cart_id bigint null,
    potion_sku text null,
    constraint cart_items_pkey primary key (id),
    constraint cart_items_potion_sku_fkey foreign key (potion_sku) references potions (sku),
    constraint public_cart_items_cart_id_fkey foreign key (cart_id) references carts (id),
    constraint cart_items_quantity_check check ((quantity > 0))
  ) tablespace pg_default;

  create table
  public.carts (
    id bigint generated by default as identity,
    customer text null,
    constraint carts_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public.general_ledger (
    id bigint generated by default as identity,
    field_name text not null,
    quantity integer not null default 0,
    transaction_id bigint null,
    constraint ledger_entries_pkey primary key (id),
    constraint ledger_entries_transaction_id_fkey foreign key (transaction_id) references transactions (id)
  ) tablespace pg_default;

  create table
  public.magic (
    id bigint generated by default as identity,
    min_threshold integer null default 0,
    min_potions integer null default 0,
    constraint magic_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public.potion_ledger (
    id bigint generated by default as identity,
    potion_sku text null,
    quantity integer not null default 0,
    transaction_id bigint null,
    constraint potion_ledger_pkey primary key (id),
    constraint potion_ledger_potion_sku_fkey foreign key (potion_sku) references potions (sku),
    constraint potion_ledger_transaction_id_fkey foreign key (transaction_id) references transactions (id)
  ) tablespace pg_default;

  create table
  public.potions (
    sku text not null,
    price integer null default 0,
    num_red_ml integer null default 0,
    num_green_ml integer null default 0,
    num_blue_ml integer null default 0,
    num_dark_ml integer null default 0,
    constraint potions_pkey primary key (sku),
    constraint potions_sku_key unique (sku)
  ) tablespace pg_default;

  create table
  public.transactions (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    description text null,
    constraint account_transactions_pkey primary key (id)
  ) tablespace pg_default;