create table
  public.global_inventory (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    num_green_potions integer null default 0,
    num_green_ml integer null default 0,
    gold integer null default 0,
    num_red_potions integer null default 0,
    num_red_ml integer null default 0,
    num_blue_potions integer null default 0,
    num_blue_ml integer null default 0,
    num_dark_ml integer null default 0,
    constraint global_inventory_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public.carts (
    id bigint generated by default as identity,
    customer text null,
    constraint carts_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public.cart_items (
    id bigint generated by default as identity,
    quantity integer null default 0,
    cart_id bigint null,
    potion_id bigint null,
    constraint cart_items_pkey primary key (id),
    constraint public_cart_items_cart_id_fkey foreign key (cart_id) references carts (id),
    constraint public_cart_items_potion_id_fkey foreign key (potion_id) references potions (id),
    constraint cart_items_quantity_check check ((quantity > 0))
  ) tablespace pg_default;

  create table
  public.magic (
    id bigint generated by default as identity,
    min_threshold integer null default 0,
    min_potions integer null default 0,
    constraint magic_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public.potions (
    id bigint generated by default as identity,
    sku text not null,
    inventory integer null default 0,
    price integer null default 0,
    num_red_ml integer null default 0,
    num_green_ml integer null default 0,
    num_blue_ml integer null default 0,
    num_dark_ml integer null default 0,
    constraint potions_pkey primary key (id),
    constraint potions_sku_key unique (sku)
  ) tablespace pg_default;